#!/bin/zsh -f
# Graphical fuzzy selector for use in personal scripts

_select_fzf() {
    local -a opts=(

)
    fzf $opts
}

_select_rofi() {
    local -a opts=(
        -dpi
        -keep-right
        -dmenu
        -i
        -p $title
        -multi-select
    )
    rofi $opts
}
